const quizFragen = [{
    frage: "Wie lange dauert der 30-jährige Krieg?",
    A: "30 Jahre",
    B: "29 Jahre",
    C: "300 Jahre",
    D: "31 Jahre",
    richtig: "A",
}, {
    frage: "Einige Monate haben 30, einige 31 Tage. Wie viele haben 28 Tage?",
    A: "Alle",
    B: "1",
    C: "0",
    D: "2",
    richtig: "A",
}, {
    frage: "Wie viele Buchstaben hat das hawaiianische Alphabet?	",
    A: "13",
    B: "45",
    C: "23",
    D: "12",
    richtig: "D",
}, {
    frage: "Welches Land ist flächenmäßig das zweitgrößte der Erde?",
    A: "USA",
    B: "China",
    C: "Kanada",
    D: "Russland",
    richtig: "C",
}, {
    frage: "Welches ist die größte Stadt der Welt?	",
    A: "New York",
    B: "Paris",
    C: "Los Angeles",
    D: "Mexiko-City",
    richtig: "D",
}, {
    frage: "Wie heißt die Hauptstadt von Brasilien?	",
    A: "Rio de Janeiro",
    B: "Brasilia",
    C: "Brassilia",
    D: "Fontolos",
    richtig: "B",
}, {
    frage: "In welchem Jahr war die Einführung des Euro?",
    A: "2002",
    B: "2000",
    C: "1999",
    D: "2001",
    richtig: "A",
}, ]